<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form method="post" action="/signUp">
    <label for="login">login:</label><br>
    <input type="text" id="login" name="login"><br>
    <label for="email">email:</label><br>
    <input type="text" id="email" name="email"><br>
    <label for="country">country:</label><br>
    <input type="text" id="country" name="country">
    <label for="password">password:</label><br>
    <input type="text" id="password" name="password">
</form>
</body>
</html>